#!/usr/bin/expect
spawn make install
expect "install_root:"
send "\r"
expect "tempdir:"
send "/tmp/extmail\r"
expect "config_directory:"
send "\r"
expect "command_directory:"
send "\r"
expect "daemon_directory:"
send "\r"
expect "data_directory:"
send "\r"
expect "html_directory:"
send "\r"
expect "mail_owner:"
send "\r"
expect "mailq_path:"
send "\r"
expect "manpage_directory:"
send "\r"
expect "newaliases_path:"
send "\r"
expect "queue_directory:"
send "\r"
expect "readme_directory:"
send "\r"
expect "sendmail_path:"
send "\r"
expect "setgid_group:"
send "\r"
expect "shlib_directory:"
send "\r"
expect "meta_directory:"
send "\r"

interact